### ISSUE TITLE
Use CSS3’s ch unit for indenting text.

### ISSUE THREAD

**Issue by Zegnat** [mrcoles/markdown-css#5]
CSS3 introduces [the `ch` unit](http://www.w3.org/TR/css3-values/#ch-unit) of length ([MDN](https://developer.mozilla.org/docs/CSS/length)). This is exactly as much horizontal space as the character `0` occupies, and thus for a monotype font as much horizontal space as any character. By using this unit you could make sure (e.g.) code blocks are indented exactly 4 spaces:

``` css
.markdown pre {
  margin-left: 4ch;
}
```

Because CSS parsers ignore anything they don’t understand it is easy to create [fallback methods](http://snook.ca/archives/html_and_css/font-size-with-rem) for units:

``` css
.markdown pre {
  margin-left: 36px;
  margin-left: 4ch; /* Only picked up by browsers that know `ch`. */
}
```

This would make for a much neater aligned text. I’ll see if I can do a pull request later, maybe someone else can get there before me.
